### ISSUE TITLE
Chapter 2: Block Break Message

### ISSUE THREAD

**Issue by LironahWulfe** [AdityaGupta1/minecraft-modding-book#30]
Hi,

My son and I are working through the lesson in chapter 2, but much of the code seems to have changed since the book was published. We have managed to find updated commands for each deprecated piece of the lesson and gotten all of our errors to go away, but the block break message still does not appear when we run our modded version. We have confirmed that the mod is loading.

Here is the code for our Main.java file:

package org.devoxx4kids.forge.mods;

import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;

@Mod(modid = Main.MODID, version = Main.VERSION)
public class Main {
	public static final String MODID ="myMods";
	public static final String VERSION = "1.0";
	
	@EventHandler
	public void init(FMLInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(new BlockBreakMessage());
	}
}

And here is the code we have come up with for BlockBreakMessage.java, based on suggestions elsewhere in this forum:

package org.devoxx4kids.forge.mods;

import net.minecraft.util.text.TextComponentString;
import net.minecraft.util.text.TextFormatting;
import net.minecraftforge.event.world.BlockEvent.BreakEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

public class BlockBreakMessage {
	@SubscribeEvent
	public void sendMessage(BreakEvent event) {
		event.getPlayer().sendMessage(new TextComponentString(TextFormatting.GOLD + "You broke a block!"));
	}
}

Again, all error messages disappear when we use this code, but the block break message does not appear, nor do any errors related to the mod appear in the console. Please advise.

Is there an addendum somewhere which updates it to the current version of JDK, or would we be better off sending the book back and looking for something current? He would really prefer to not be working with deprecated code.

**Comment by AdityaGupta1** [comment]
Hi,

Can you please list the exact versions of Forge, JDK, etc. that you are using, along with pasting the console log here? If it's too long you can put it into a site like https://pastebin.com/ and link it here.

**Comment by LironahWulfe** [comment]
We are using Java SE Development Kit Update 231 (64-bit), Forge 1.12.2-14.23.5.2768, Minecraft 1.12.2, and the problem persists despite my updating Java itself this morning. We are running Windows 7. I also have an older version of Forge on the machine (not running); could this be affecting our build? I have already tried rolling back and then reinstalling everything according to the tutorial on this site.

Console log:
[10:34:03] [main/INFO] [GradleStart]: Extra: []
[10:34:03] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --assetsDir, C:/Users/Lironah/.gradle/caches/minecraft/assets, --assetIndex, 1.12, --accessToken{REDACTED}, --version, 1.12.2, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[10:34:03] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[10:34:03] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[10:34:03] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[10:34:03] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[10:34:03] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2768 for Minecraft 1.12.2 loading
[10:34:03] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_241, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_241
[10:34:03] [main/ERROR] [FML]: Apache Maven library folder was not in the format expected. Using default libraries directory.
[10:34:03] [main/ERROR] [FML]: Full: C:\Users\Lironah\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-artifact\3.5.3\7dc72b6d6d8a6dced3d294ed54c2cc3515ade9f4\maven-artifact-3.5.3.jar
[10:34:03] [main/ERROR] [FML]: Trimmed: c:/users/lironah/.gradle/caches/modules-2/files-2.1/org.apache.maven/maven-artifact/3.5.3/
[10:34:03] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[10:34:03] [main/INFO] [FML]: Detected deobfuscated environment, loading log configs for colored console logs.
2020-02-02 10:34:05,181 main WARN Disabling terminal, you're running in an unsupported environment.
[10:34:05] [main/INFO] [FML]: Ignoring missing certificate for coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin), we are in deobf and it's a forge core plugin
[10:34:05] [main/INFO] [FML]: Ignoring missing certificate for coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin), we are in deobf and it's a forge core plugin
[10:34:05] [main/INFO] [FML]: Searching C:\Users\Lironah\Desktop\MinecraftModding\forge\run\.\mods for mods
[10:34:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[10:34:05] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[10:34:05] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[10:34:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:34:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[10:34:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[10:34:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:34:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:34:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:34:08] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[10:34:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:34:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[10:34:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[10:34:09] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[10:34:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[10:34:09] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[10:34:10] [main/INFO] [minecraft/Minecraft]: Setting user: Player573
[10:34:14] [main/WARN] [minecraft/GameSettings]: Skipping bad option: lastServer:
[10:34:14] [main/INFO] [minecraft/Minecraft]: LWJGL Version: 2.9.4
[10:34:16] [main/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 817340520 bytes (779 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.4.0' Renderer: 'GeForce GT 610/PCIe/SSE2'
[10:34:16] [main/INFO] [FML]: MinecraftForge v14.23.5.2768 Initialized
[10:34:16] [main/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[10:34:17] [main/INFO] [FML]: Replaced 1036 ore ingredients
[10:34:17] [main/INFO] [FML]: Searching C:\Users\Lironah\Desktop\MinecraftModding\forge\run\.\mods for mods
[10:34:17] [main/ERROR] [FML]: Unable to construct net.minecraftforge.fml.common.Mod container
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.common.ModContainerFactory.build(ModContainerFactory.java:73) [ModContainerFactory.class:?]
	at net.minecraftforge.fml.common.discovery.DirectoryDiscoverer.exploreFileSystem(DirectoryDiscoverer.java:135) [DirectoryDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.DirectoryDiscoverer.exploreFileSystem(DirectoryDiscoverer.java:104) [DirectoryDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.DirectoryDiscoverer.exploreFileSystem(DirectoryDiscoverer.java:104) [DirectoryDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.DirectoryDiscoverer.exploreFileSystem(DirectoryDiscoverer.java:104) [DirectoryDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.DirectoryDiscoverer.exploreFileSystem(DirectoryDiscoverer.java:104) [DirectoryDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.DirectoryDiscoverer.discover(DirectoryDiscoverer.java:62) [DirectoryDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:425) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:513) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:421) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:25) [start/:?]
Caused by: java.lang.IllegalArgumentException: The modId myMods must be all lowercase.
	at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:146) ~[FMLModContainer.class:?]
	at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:130) ~[FMLModContainer.class:?]
	... 32 more
[10:34:19] [main/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[10:34:19] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 218068238 nanos
[10:34:19] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, examplemod] at CLIENT
[10:34:19] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, examplemod] at SERVER
[10:34:20] [main/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Example Mod
[10:34:20] [main/INFO] [FML]: Processing ObjectHolder annotations
[10:34:20] [main/INFO] [FML]: Found 1168 ObjectHolder annotations
[10:34:20] [main/INFO] [FML]: Identifying ItemStackHolder annotations
[10:34:20] [main/INFO] [FML]: Found 0 ItemStackHolder annotations
[10:34:20] [main/INFO] [FML]: Configured a dormant chunk cache size of 0
[10:34:20] [main/INFO] [FML]: Applying holder lookups
[10:34:20] [main/INFO] [FML]: Holder lookups applied
[10:34:20] [main/INFO] [FML]: Applying holder lookups
[10:34:20] [main/INFO] [FML]: Holder lookups applied
[10:34:20] [main/INFO] [FML]: Applying holder lookups
[10:34:20] [main/INFO] [FML]: Holder lookups applied
[10:34:20] [main/INFO] [FML]: Applying holder lookups
[10:34:20] [main/INFO] [FML]: Holder lookups applied
[10:34:20] [main/INFO] [FML]: Injecting itemstacks
[10:34:20] [main/INFO] [FML]: Itemstack injection complete
[10:34:20] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[10:34:21] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: UP_TO_DATE Target: null
[10:34:30] [Sound Library Loader/INFO] [minecraft/SoundManager]: Starting up SoundSystem...
[10:34:30] [Thread-5/INFO] [minecraft/SoundManager]: Initializing LWJGL OpenAL
[10:34:30] [Thread-5/INFO] [minecraft/SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[10:34:31] [Thread-5/INFO] [minecraft/SoundManager]: OpenAL initialized.
[10:34:31] [Sound Library Loader/INFO] [minecraft/SoundManager]: Sound engine started
[10:34:40] [main/INFO] [FML]: Max texture size: 16384
[10:34:40] [main/INFO] [minecraft/TextureMap]: Created: 512x512 textures-atlas
[10:34:42] [main/INFO] [FML]: Applying holder lookups
[10:34:42] [main/INFO] [FML]: Holder lookups applied
[10:34:42] [main/INFO] [examplemod]: DIRT BLOCK >> minecraft:dirt
[10:34:42] [main/INFO] [FML]: Injecting itemstacks
[10:34:42] [main/INFO] [FML]: Itemstack injection complete
[10:34:42] [main/INFO] [FML]: Forge Mod Loader has successfully loaded 5 mods
[10:34:42] [main/WARN] [minecraft/GameSettings]: Skipping bad option: lastServer:
[10:34:42] [main/INFO] [mojang/NarratorWindows]: Narrator library for x64 successfully loaded
[10:34:44] [Realms Notification Availability checker #1/INFO] [mojang/RealmsClient]: Could not authorize you against Realms server: Invalid session id
[10:34:49] [Server thread/INFO] [minecraft/IntegratedServer]: Starting integrated minecraft server version 1.12.2
[10:34:49] [Server thread/INFO] [minecraft/IntegratedServer]: Generating keypair
[10:34:49] [Server thread/INFO] [FML]: Injecting existing registry data into this server instance
[10:34:49] [Server thread/INFO] [FML]: Applying holder lookups
[10:34:49] [Server thread/INFO] [FML]: Holder lookups applied
[10:34:50] [Server thread/INFO] [FML]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@6d3b1c34)
[10:34:50] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 488 advancements
[10:34:51] [Server thread/INFO] [FML]: Loading dimension -1 (New World) (net.minecraft.server.integrated.IntegratedServer@6d3b1c34)
[10:34:51] [Server thread/INFO] [FML]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@6d3b1c34)
[10:34:51] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for level 0
[10:34:52] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 6%
[10:34:53] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 73%
[10:34:53] [Server thread/INFO] [FML]: Unloading dimension -1
[10:34:53] [Server thread/INFO] [FML]: Unloading dimension 1
[10:34:53] [Server thread/INFO] [minecraft/IntegratedServer]: Changing view distance to 12, from 10
[10:34:56] [Netty Local Client IO #0/INFO] [FML]: Server protocol version 2
[10:34:56] [Netty Server IO #1/INFO] [FML]: Client protocol version 2
[10:34:56] [Netty Server IO #1/INFO] [FML]: Client attempting to join with 5 mods : minecraft@1.12.2,FML@8.0.99.99,forge@14.23.5.2768,mcp@9.42,examplemod@1.0
[10:34:56] [Netty Local Client IO #0/INFO] [FML]: [Netty Local Client IO #0] Client side modded connection established
[10:34:56] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[10:34:56] [Server thread/INFO] [minecraft/PlayerList]: Player573[local:E:b9d12b7a] logged in with entity id 384 at (-264.40861433482337, 73.0, 202.54982856263538)
[10:34:56] [Server thread/INFO] [minecraft/MinecraftServer]: Player573 joined the game
[10:34:57] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
[10:34:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'New World'/overworld
[10:35:16] [pool-2-thread-1/WARN] [mojang/YggdrasilMinecraftSessionService]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@6295d777[id=47924d91-5a7e-38eb-bebd-89bd771037e9,name=Player573,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[YggdrasilAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [YggdrasilMinecraftSessionService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:60) [YggdrasilMinecraftSessionService$1.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:57) [YggdrasilMinecraftSessionService$1.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) [guava-21.0.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:170) [YggdrasilMinecraftSessionService.class:?]
	at net.minecraft.client.Minecraft.getProfileProperties(Minecraft.java:3181) [Minecraft.class:?]
	at net.minecraft.client.resources.SkinManager$3.run(SkinManager.java:138) [SkinManager$3.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[10:35:17] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
[10:35:17] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'New World'/overworld
[10:35:19] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[10:35:19] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[10:35:19] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: Player573 lost connection: Disconnected
[10:35:19] [Server thread/INFO] [minecraft/MinecraftServer]: Player573 left the game
[10:35:19] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: Stopping singleplayer server as player logged out
[10:35:19] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[10:35:19] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'New World'/overworld
[10:35:19] [Server thread/INFO] [FML]: Unloading dimension 0
[10:35:19] [Server thread/INFO] [FML]: Applying holder lookups
[10:35:19] [Server thread/INFO] [FML]: Holder lookups applied
[10:35:23] [main/INFO] [minecraft/Minecraft]: Stopping!
[10:35:23] [main/INFO] [minecraft/SoundManager]: SoundSystem shutting down...
[10:35:23] [main/WARN] [minecraft/SoundManager]: Author: Paul Lamb, www.paulscode.com
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by AdityaGupta1** [comment]
`Caused by: java.lang.IllegalArgumentException: The modId myMods must be all lowercase.`

Looks like it now requires you to make the modId entirely lowercase. This seems to be a recent issue based on threads I read. Try making it lowercase and see if it works.

**Comment by LironahWulfe** [comment]
It does, thank you!
